services:
  - type: web
    name: docx-to-pdf
    env: node
    buildCommand: apt-get install -y libreoffice && npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 3000
